/**
 * 表单限制常量
 */
export const limit = {
  MAX_NAME_LEN: '30',
  MAX_DESC_LEN: '100',
  MAX_PWD_LEN: '16',
  MIN_PWD_LEN: '6',
  MAX_ACCOUNT_LEN: '50',
  MAX_USERNAME_LEN: '50',
  MAX_PASSWORD_LEN: '16',
  TAG_LIST_MAX_LEN: 20,
  POSITION_LIST_MAX_LEN: 20,
  MAX_POSITION_LEN: 100,
  PAGE_SIZE: 50,
  MAX_CUSTOMER_GROUP_LEN: 200,
  MAX_POI_UPLOAD_LEN: 100,
  POI_UPLOAD_FILE_MAX_LEN: 1,
  MAX_UNION_SIZE: 10,
  MAX_INTERSECTION_SIZE: 5,
  MAX_POI_LEN: 100,
  MAX_PRIVATE_TAG_LEN: '200',
  MAX_PRIVATE_TAG_NAME_LEN: '16',
  MAX_PRIVATE_TAG_DESC_LEN: '24'
};
